export default {
  sourceDir: "examples/demo-nextjs/src",
  localesDir: "examples/demo-nextjs/locales",
  languages: ["en", "ar", "fr", "de"],
  ignore: ["node_modules", "dist", "build", ".next", ".git"],
  localeStructure: {
    format: "js",
    structure: "multiple",
    splitStrategy: "page",
    commonFile: true,
    naming: "camel",
  },
  cacheTranslations: true,
  dynamicExtraction: false,
  translationInstructions: [
    "This is a Next.js marketing application.",
    "Keep marketing copy and CTA labels short, natural, and persuasive.",
    "Do not translate brand names or product names unless they are already localized.",
  ],
  sourceLocale: "en",
  openAiModel: "gpt-4o-mini",
  geminiModel: "gemini-2.5-flash-lite",
  aiBatchSize: 20,
  translationImportPath: "@/i18n",
  translationFunctionName: "t",
};
